### ISSUE TITLE
UI reporting - RSB objects unsorted in rules report tab

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#1651]
sorting seems to be removed (or never implemented?) in report tab of RSB

**Comment by tpurschke** [comment]
Example to reproduces issue:
When removing rule_id where statement, sorting works.

```graphql
query queryABC (
  $importId: bigint
  $limit: Int
  $offset: Int
) {
  view_rule_nwobj_resolved_sorted (
      limit: $limit
      offset: $offset
      where: { 
        _or:  [
          {rule_id: { _eq: 125 }}
          {rule_id: { _eq: 127 }}
          {rule_id: { _eq: 121 }}
          {rule_id: { _eq: 123 }}
        ]
        #{created: { _lte: $importId }}
        #{removed: { _gte: $importId }}
  		}
      distinct_on: [obj_id]
    ) {
      object {
        obj_name
      }
  }
} 
```
variables:
```json
{"limit":300,"offset":0} 
```

**Comment by Y4nnikH** [comment]
### Current state of things

#### Original Problem:
We want the objects to be distinct, which we can achieve by using
```
distinct_on: [obj_id]
```
, but also to be ordered by their name, which by itself could be achieved with
```
order_by: {object: {obj_name: desc}}
```
However, the column specified in the `distinct` statement must match the one we are ordering by, meaning the two cannot be used together.

#### First Approach
Create a view, sorting the rows in the relevant object table by name, hoping the query will thus also pick them in the alphabetical order (it doesn't), resulting in a sorted output.
-> Doesn't work, problem seems to be, that the `where` statement checking for the rule_id's changes the order in which the query views the rows.

#### Second Idea
Have the obj_id's we are using in the `distinct` statement correspond to the alphabetical order.
-> Doesn't work, because the importer periodically adds new objects to the table, whose id's cannot be sorted into the existing set of objects from older imports
