### ISSUE TITLE
RSB: reported rule deselect issue

### ISSUE THREAD

**Issue by abarz722** [CactuseSecurity/firewall-orchestrator#2168]
when selecting several rules of a rule report, in the rule tab in right sidebar: 
after deselecting one of the rules, sometimes the objects of the wrong rule remain displayed

**Comment by tpurschke** [comment]
@Y4nnikH could you have a look at this?

**Comment by Y4nnikH** [comment]
To reproduce the bug in the most simple way: 1. select rule *A*, 2. select rule *B*, 3. deselect rule *A* -> rsb will show rule *A* instead of *B*.

After searching for quite a bit, I found that the issue lies with the rerendering of the objectgroup components. (An objectgroup always contains and displays the data (nwobjects, services, users) of one rule).

First of all, the list of selected rules, for which the objectgroups were rendered, was always correct. So the correct rules should have been rendered in the RSB at every time point. But the way I designed the objectgroup component's "state" does apparently not fit how rerendering in blazor works. For future reference - mostly for myself - (and possible other issues with this), I will try to write a little bit about it here.

In general, the objectgroup may not be given the full data when it is being initialized, since we dont want to fetch all data before it is needed. (we lazy fetch e.g. the network objects only as soon as the corresponding collapse is opened for the first time). Because of that, the objectgroup has a parameter `InitialContent`, where it takes an empty rule or management (no objects fetched yet). During initialization, the `Content` variable is set to `InitialContent` and after that updated for each fetch. The html in the component is always rendered according to `Content`, so that it shows updated data. However, this seems to be a problem with how blazor's rerendering works. The behaviour I expected was, that an instance of an objectgroup component will always be associated with the rule data it was initialized on. So if component *X* was initialized with rule data *A*, and rule *A* was unselected, component *X* would be disposed. What blazor's rerendering might do however is the following:

Suppose rule *A* and rule *B* are selected, and rule *A* is being unselected. In the RSB, where component *X* (containing *A*'s data) and *Y* (*B*'s data) are still rendered, it will now in order rerender the components for all rules in the selected rules list ( [*B*] ) *on top* of the existing components. So the parameters of component *X* will be overwritten with the data of *B*, and component *Y* will be disposed (as there is no more data in the list). This means that `InitialContent` of *X* will now be the data of *B*, but `Content` will be rendered, which is still the data of *A*, and the wrong rule is being shown.

At least from my observations, that is my guess as to how it works.

With that knowledge, there is now a nicer way to handle the data in ObjectGroup components from the outside, which I will implement soon.
